# Generated by Django 6.0 on 2025-12-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("guilds", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, help_text="Event timestamp from game server", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="details",
            field=models.JSONField(help_text="Event-specific details in JSON format"),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("PLAYER_KILL", "Player Kill"),
                    ("DUNGEON_CLEAR", "Dungeon Clear"),
                    ("ITEM_PURCHASE", "Item Purchase"),
                    ("GUILD_JOIN", "Guild Join"),
                    ("GUILD_LEAVE", "Guild Leave"),
                    ("PLAYER_LEVEL_UP", "Player Level Up"),
                    ("QUEST_COMPLETE", "Quest Complete"),
                    ("MARKET_TRANSACTION", "Market Transaction"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Type of event in the MMORPG (e.g., PLAYER_KILL, DUNGEON_CLEAR)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["type", "-created_at"], name="events_even_type_52d8c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["player", "-created_at"], name="events_even_player__0c74b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["guild", "-created_at"], name="events_even_guild_i_038776_idx"
            ),
        ),
    ]
