# Generated by Django 6.0 on 2025-12-10 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_alter_event_options_event_timestamp_and_more"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("GUILD_HARMONY", "Guild Harmony"),
                            ("SOLO_CLEAR", "Solo Clear"),
                            ("REVENGE_AWARD", "Revenge Award"),
                            ("RIVAL_SLAYER", "Rival Slayer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_granted",
                        to="events.event",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards_earned",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("player", "award_type", "event")},
            },
        ),
    ]
